- name: Robomongo | Check if my_package is installed
  command: dpkg-query -W robomongo
  register: robomongo_check_deb
  sudo: yes
  failed_when: robomongo_check_deb.rc > 1
  changed_when: robomongo_check_deb.rc == 1
  tags:
    -worktools
    -robomongo


- name: Robomongo | download package
  get_url: 
    url="http://robomongo.org/files/linux/robomongo-{{ robomongo_version }}-x86_64.deb"
    dest="/home/{{ deploy_user }}/Downloads/robomongo.deb"
  when: robomongo_check_deb.rc == 1
  tags:
    -worktools
    -robomongo  

- name: Robomongo | install package
  apt: deb="/home/{{ deploy_user }}/Downloads/robomongo.deb"
  sudo: true
  when: robomongo_check_deb.rc == 1
  tags:
    -worktools
    -robomongo  
