- name: DBeawer | Check if my_package is installed
  command: dpkg-query -W dbeaver
  register: dbeawer_check_deb
  become: yes
  failed_when: dbeawer_check_deb.rc > 1
  changed_when: dbeawer_check_deb.rc == 1
  tags:
    -worktools
    -dbeawer

- name: DBeawer | download package
  get_url:
    url="http://dbeaver.jkiss.org/files/dbeaver-ce_latest_amd64.deb"
    dest="/tmp/dbeawer.deb"
  when: dbeawer_check_deb.rc == 1 and (dbeawer_version == "latest")
  tags:
    -worktools
    -dbeawer


- name: DBeawer | download package
  get_url:
    url="http://dbeaver.jkiss.org/files/{{ dbeawer_version }}/dbeaver-ce_{{ dbeawer_version }}_amd64.deb"
    dest="/tmp/dbeawer.deb"
  when: dbeawer_check_deb.rc == 1 and not (dbeawer_version == "latest")
  tags:
    -worktools
    -dbeawer


- name: DBeawer | install package
  apt: deb="/tmp/dbeawer.deb"
  become: true
  when: dbeawer_check_deb.rc == 1
  tags:
    -worktools
    -dbeawer
