- name: Robomongo | Check if my_package is installed
  command: dpkg-query -W robomongo
  register: robomongo_check_deb
  become: yes
  failed_when: robomongo_check_deb.rc > 1
  changed_when: robomongo_check_deb.rc == 1
  tags:
    -worktools
    -robomongo


- name: Robomongo | download package
  get_url: 
    url="https://download.robomongo.org/{{ robomongo_version }}/linux/robomongo-{{ robomongo_version }}-x86_64.deb"
    dest="/home/{{ deploy_user }}/Downloads/robomongo.deb"
  when: robomongo_check_deb.rc == 1
  tags:
    -worktools
    -robomongo  

- name: Robomongo | install package
  apt: deb="/home/{{ deploy_user }}/Downloads/robomongo.deb"
  become: true
  when: robomongo_check_deb.rc == 1
  tags:
    -worktools
    -robomongo  
